"""JSON output pipeline variant.

Same flow as pipeline.py (index → standardize → triage → preprocess → infer)
but results are written to a local JSON file instead of image metadata. The
image files are never touched, which is what makes this mode usable on a
collection that is hashed, read-only, or simply not yours to edit.

Keywords are generated by default. Descriptions are generated too when a
caption option is given (--short-caption, --detailed-caption), exactly as in
the metadata pipeline: this variant chooses where results go, not what is
asked of the model.

Each record keeps what each model produced separately, under "runs", alongside
the union of their keywords under "keywords":

    "E:/img/a.jpg": {
        "file": "a.jpg",
        "keywords": ["cat", "sofa", "tabby"],
        "description": "A tabby cat asleep on a sofa.",
        "runs": {
            "CapRL-3B": ["cat", "sofa"],
            "InternVL3.5-8B": {"keywords": ["cat", "tabby"],
                               "description": "A tabby cat asleep on a sofa."}
        }
    }

Consumers that only know about "keywords" are unaffected. Consumers that
understand "runs" can tell a tag two models agreed on from one a single model
guessed at -- a distinction that is impossible to recover once the lists are
unioned, and the main reason to run more than one model in the first place.

A run is a bare list when that model produced no description and a dict when it
did, so files written before descriptions existed still read correctly and
files written without captions keep their old shape.
"""
import json
import os
import time
import uuid

from . import metadata_io
from .pipeline import FileProcessor


def run_keywords(run):
    """Keywords from one run, which is a bare list or a dict with a description.
    """
    
    if isinstance(run, dict):
        return run.get("keywords") or []
    return run or []


class JsonFileProcessor(FileProcessor):
    """FileProcessor variant that writes keyword results to a JSON file.

    Differences from FileProcessor:
    - Results are accumulated in memory and flushed to a JSON file after
      each successful image; nothing is written back to image metadata.
    - Processed-file tracking uses the JSON file itself rather than the
      UUID/Status XMP tags embedded in each image.
    """

    def __init__(self, config, check_paused_or_stopped=None, callback=None):
        super().__init__(config, check_paused_or_stopped, callback)
        self.json_output_file = getattr(config, "json_output_file", "image_tags.json")
        self._json_results = {}
        # Load regardless of reprocess_all
        if os.path.exists(self.json_output_file):
            try:
                with open(self.json_output_file, "r", encoding="utf-8") as f:
                    self._json_results = json.load(f)
                self.callback(
                    f"Loaded {len(self._json_results)} existing entries "
                    f"from {self.json_output_file}"
                )
            except Exception as e:
                self.callback(f"Warning: could not load existing JSON output: {e}")

    def check_uuid(self, metadata, file_path):
        """Skip files already present in the JSON output (unless reprocess_all).
        """
        
        if not self.config.reprocess_all and file_path in self._json_results:
            return None
            
        # Assign a temporary identifier so the rest of the pipeline doesn't
        # break; it is never written back to the image file.
        if not metadata.get("XMP:Identifier"):
            metadata["XMP:Identifier"] = str(uuid.uuid4())
        return metadata

    def _validate(self, metadata, file_path):
        """Reject only files with hard ExifTool errors; writability is irrelevant.
        """
        
        parts = metadata.get("ExifTool:Validate", "0 0 0").split()
        try:
            errors = int(parts[0]) if parts else 0
        except ValueError:
            errors = 0
        if errors > 0:
            print(f"Validation Failed: {os.path.basename(file_path)}")
            self.callback(f"Validation failed: {file_path}")
            self.failed_validations.append(file_path)
            self.callback("---")
            return False
        return True


    def caption_wanted(self):
        """Did the user ask for a description, as opposed to keywords alone?
        """
        
        return (not self.config.no_caption
                and (self.config.short_caption or self.config.detailed_caption))

    def _process_one(self, metadata, processed_image, error=None):
        """Run LLM generation for one file and store the result in the JSON dict.
        """
        
        try:
            file_path = metadata["SourceFile"]

            if error is not None:
                print(f"Image Processing Error: {os.path.basename(file_path)}: {error}")
                self.callback(f"Image processing error for {file_path}: {error}")
                if self.config.rename_invalid:
                    metadata_io.rename_to_invalid(file_path, self.callback)
                self.callback("---")
                return

            if not processed_image:
                self.callback(f"Failed to process image: {file_path}")
                if self.config.rename_invalid:
                    metadata_io.rename_to_invalid(file_path, self.callback)
                self.callback("---")
                return

            filetype = metadata.get(
                "File:FileType",
                self.get_file_type(os.path.splitext(file_path)[1]),
            )
            print(f"Processing: {os.path.basename(file_path)} [{filetype}]")

            start_time = time.time()
            updated_metadata = self.generate_metadata(metadata, processed_image)
            status = updated_metadata.get("XMP:Status")

            if not self.config.quick_fail and status == "retry":
                print(f"AI Generation Issue - Retrying: {os.path.basename(file_path)}")
                self.callback(f"Asking AI to try again for {file_path}...")
                self.callback("---")
                updated_metadata = self.generate_metadata(metadata, processed_image)
                status = updated_metadata.get("XMP:Status")

            keywords = updated_metadata.get("MWG:Keywords") or []
            # Only a description this run generated is recorded
            description = ((updated_metadata.get("MWG:Description") or "")
                           if self.caption_wanted() else "")
            success = status == "success"

            if self.config.fix_extension and success:
                expected_ext = metadata.get("File:FileTypeExtension")
                if expected_ext:
                    new_path = metadata_io.fix_file_extension(
                        file_path, expected_ext, self.callback
                    )
                    if new_path != file_path:
                        file_path = new_path

            if success and not self.config.dry_run:
                self._record_run(file_path, keywords, description)
                self._flush_json()

            if success:
                self.callback(
                    {
                        "type": "image_data",
                        "base64_image": processed_image,
                        "caption": description,
                        "keywords": keywords,
                        "file_path": file_path,
                    }
                )

            processing_time = time.time() - start_time
            self.total_processing_time += processing_time
            self.files_completed += 1
            self._report(file_path, status, processing_time, success)

        except Exception as e:
            file_path = metadata.get("SourceFile", "?")
            print(f"Processing Error: {os.path.basename(file_path)}: {e}")
            self.callback(f"<b>Error processing:</b> {file_path}: {e}")
            self.callback("---")

    def process_directory(self, directory):
        super().process_directory(directory)
        if not self.config.dry_run and self._json_results:
            abs_path = os.path.abspath(self.json_output_file)
            self.callback(f"<b>JSON output written to:</b> {abs_path}")
            self.callback(f"<b>Total entries:</b> {len(self._json_results)}")

    def _record_run(self, file_path, keywords, description=""):
        """Store this model's result, keeping any other model's run intact.
        """
        
        model = self.llm_processor.model_name()
        record = self._json_results.get(file_path) or {}
        runs = record.get("runs")
        if not isinstance(runs, dict):
            # First time this record gains provenance.
            previous = record.get("keywords") or []
            runs = {"unattributed": list(previous)} if previous else {}
        # A run stays a list of keywords until there is a description
        runs[model] = ({"keywords": list(keywords), "description": description}
                       if description else list(keywords))

        merged = {}
        for run in runs.values():
            for keyword in run_keywords(run):
                merged.setdefault(keyword, None)

        entry = {"file": os.path.basename(file_path), "keywords": list(merged)}
        latest = description or record.get("description") or ""
        if latest:
            entry["description"] = latest
        entry["runs"] = runs
        self._json_results[file_path] = entry

    def _flush_json(self):
        """Write accumulated results to the JSON output file atomically.
        """
        
        try:
            tmp = self.json_output_file + ".tmp"
            with open(tmp, "w", encoding="utf-8") as f:
                json.dump(self._json_results, f, indent=2, ensure_ascii=False)
            os.replace(tmp, self.json_output_file)
        except Exception as e:
            self.callback(f"Warning: could not write JSON output: {e}")
